// BlockNote default-shape document templates.
// Block.id is generated by BlockNote on insert, so we leave it off here and
// let the editor assign one when the page is opened.

export interface PageTemplate {
  key: string;
  label: string;
  emoji: string;
  description: string;
  title: string;
  content: unknown[];
}

function h(level: 1 | 2 | 3, text: string) {
  return {
    type: "heading",
    props: { level },
    content: [{ type: "text", text, styles: {} }],
  };
}
function p(text = "") {
  return {
    type: "paragraph",
    content: text ? [{ type: "text", text, styles: {} }] : [],
  };
}
function bullet(text: string) {
  return {
    type: "bulletListItem",
    content: [{ type: "text", text, styles: {} }],
  };
}
function check(text: string) {
  return {
    type: "checkListItem",
    props: { checked: false },
    content: [{ type: "text", text, styles: {} }],
  };
}

export const PAGE_TEMPLATES: PageTemplate[] = [
  {
    key: "blank",
    label: "Blank page",
    emoji: "📄",
    description: "Start from scratch",
    title: "Untitled",
    content: [],
  },
  {
    key: "meeting",
    label: "Meeting notes",
    emoji: "🗒️",
    description: "Attendees, agenda, decisions, action items",
    title: "Meeting — ",
    content: [
      h(1, "Meeting notes"),
      h(3, "Attendees"),
      bullet(""),
      h(3, "Agenda"),
      bullet(""),
      h(3, "Discussion"),
      p(""),
      h(3, "Decisions"),
      bullet(""),
      h(3, "Action items"),
      check("Owner — what — by when"),
    ],
  },
  {
    key: "sop",
    label: "SOP",
    emoji: "📋",
    description: "Standard operating procedure with steps + checklist",
    title: "SOP — ",
    content: [
      h(1, "Standard Operating Procedure"),
      h(3, "Purpose"),
      p(""),
      h(3, "When to use"),
      p(""),
      h(3, "Pre-requisites"),
      bullet(""),
      h(3, "Steps"),
      check("Step 1"),
      check("Step 2"),
      check("Step 3"),
      h(3, "Failure modes / what to do if it goes wrong"),
      bullet(""),
      h(3, "Owner"),
      p(""),
    ],
  },
  {
    key: "runbook",
    label: "Runbook",
    emoji: "🚨",
    description: "Incident response playbook",
    title: "Runbook — ",
    content: [
      h(1, "Runbook"),
      h(3, "Symptom"),
      p(""),
      h(3, "Severity & paging"),
      p(""),
      h(3, "Detection"),
      bullet("Dashboard"),
      bullet("Alert"),
      h(3, "Triage"),
      check("Check upstream dependencies"),
      check("Look at recent deploys"),
      check("Check error rates"),
      h(3, "Mitigation"),
      check(""),
      h(3, "Root-cause investigation"),
      p(""),
      h(3, "Post-mortem doc link"),
      p(""),
    ],
  },
  {
    key: "onepager",
    label: "Project one-pager",
    emoji: "📑",
    description: "Single-page brief: problem, plan, success",
    title: "One-pager — ",
    content: [
      h(1, "One-pager"),
      h(3, "Problem"),
      p(""),
      h(3, "Why now"),
      p(""),
      h(3, "Proposal"),
      p(""),
      h(3, "Success metrics"),
      bullet(""),
      h(3, "Risks"),
      bullet(""),
      h(3, "Timeline"),
      bullet(""),
      h(3, "Owner & approvers"),
      p(""),
    ],
  },
  {
    key: "onetoone",
    label: "1:1 notes",
    emoji: "💬",
    description: "Recurring one-on-one agenda + history",
    title: "1:1 — ",
    content: [
      h(1, "1:1 notes"),
      h(3, "What's going well"),
      bullet(""),
      h(3, "What's blocked"),
      bullet(""),
      h(3, "Career / growth"),
      bullet(""),
      h(3, "Action items"),
      check(""),
    ],
  },
  {
    key: "onboarding",
    label: "Onboarding checklist",
    emoji: "🎉",
    description: "Week 1 checklist for a new joiner",
    title: "Onboarding — ",
    content: [
      h(1, "Welcome to the team"),
      h(2, "Day 1"),
      check("Laptop + email set up"),
      check("Slack + calendar"),
      check("Tour of the office / virtual intros"),
      h(2, "Week 1"),
      check("Read the wiki home page"),
      check("Shadow your manager"),
      check("Set up dev environment"),
      h(2, "Month 1 goals"),
      bullet(""),
    ],
  },
];

export function getTemplate(key: string): PageTemplate {
  return PAGE_TEMPLATES.find((t) => t.key === key) ?? PAGE_TEMPLATES[0];
}
